### ISSUE TITLE
Context menu for Search widget sometimes doesn't appear

### ISSUE THREAD

**Issue by shujaatak** [ubuntu/yaru_widgets.dart#4] opened 2021-11-09 14:26 UTC
I am using Ubuntu, I copied some text and then tried to paste in the Search Widget by right clicking on the Search widget to show me the context menu so that I can paste the text but it sometimes doesn't appear at all although Ctrl+V works fine.

**Comment by Feichtmeier** [comment] 2022-02-16 10:18
hi @shujaatak 
I can not reproduce this issue with current master. Is it still present?

**Comment by shujaatak** [comment] 2022-02-18 16:34
@Feichtmeier Unfortunately I can still reproduce the issue.

Follow these steps to reproduce the issue:

- Copy some text to clipboard.
- Run the Example included in the yaru_widgets.dart.
- Click on YaruRow or any other tab.
![image](https://user-images.githubusercontent.com/14161646/154722759-71532268-6006-443e-b175-3c39ce3b6486.png)
Now try to show the context menu upon Right Clicking in the Search bar, unfortunately the context menu doesn't appear. 
Now once I paste the content using CTRL+V then the Right Click Context Menu starts to appear.

**Comment by shujaatak** [comment] 2022-02-18 16:43
@Feichtmeier Also it is not the problem due to the focus of the widget as I tested that even if I bring focus to the search widget by left-clicking on it, the context menu doesn't show up on right clicking!

**Comment by shujaatak** [comment] 2022-02-18 16:44
My flutter doctor tell me: 
Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.13.0-27-generic, locale en_US.UTF-8)

**Comment by shujaatak** [comment] 2022-02-18 16:45
@Feichtmeier Can you please verify if you can reproduce this issue on your side?

**Comment by Feichtmeier** [comment] 2022-02-18 16:53
Thanks @shujaatak 
I can indeed reproduce it.
However I can reproduce it with any flutter textfield.
For example the yaru.dart example:


https://user-images.githubusercontent.com/15329494/154727107-528a9609-a4c5-4d7a-8ac4-6ba0212b2bfe.mp4

**Comment by shujaatak** [comment] 2022-02-27 12:25
[Minimal Desktop Widgets for Flutter](https://github.com/adrianos42/desktop) repository has **Context Menu** widget too.

**Comment by Feichtmeier** [comment] 2022-02-27 12:29
Thanks for the tip. I try to stay very close to material, minus the big elevation/shadows plus a little more borders here and there. Since it is not a yaru_widgets bug I close this here. Thanks for issue filing :+1:

**Closed by Feichtmeier** 2022-02-27 12:29 UTC
Labels: bug

**Comment by shujaatak** [comment] 2022-02-27 12:38
I am afraid the main issue is still not resolved i.e. Context menu for Search widget still has the issue.

**Comment by shujaatak** [comment] 2022-02-27 12:40
> Since it is not a yaru_widgets bug I close this here. 

Can you please mention if it is bug in Flutter itself or what?

**Comment by Feichtmeier** [comment] 2022-02-27 12:45
I guess either you or me could search through github/flutter/flutter and filter for "context menu" issues and see if this is already reported, yes :smiley: 
Sure, we could add replacement context menu specifically for text fields but the idea in yaru_widgets.dart is to gather "UI patterns" that make sense, arrange them, eventually adapt the Theme if adaptable in material.dart Themes (yaru.dart) and then export those patterns as widgets in this repo. Implementing a whole new context menu does not match this idea, sorry.

**Comment by Feichtmeier** [comment] 2022-02-27 13:19
@shujaatak here you go

https://github.com/flutter/flutter/issues/90563#issuecomment-1053554013
