### ISSUE TITLE
YaruWindowTitleBar adds a white line to its top border when maximised.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/yaru_widgets.dart#614] opened 2023-02-11 20:34 UTC
The line isn't there when the window is snapped to the left or right.

[Screencast from 2023-02-11 20-33-09.webm](https://user-images.githubusercontent.com/73116038/218279996-15ef55bc-a8f3-4fdf-a3f9-342a726567fe.webm)

**Comment by Jupi007** [comment] 2023-02-12 09:20
I suppose that this is related to [handy_window](https://github.com/ubuntu-flutter-community/handy_window).
But which Gtk theme are you using?
Because I can't reproduce this on ubuntu using yaru-gtk.

**Comment by Jupi007** [comment] 2023-02-12 09:24
Just tested with Adwaita, and I can reproduce this problem.

**Comment by Jupi007** [comment] 2023-02-12 09:27
@whiskeyPeak Can you open the same issue to [handy_window](https://github.com/ubuntu-flutter-community/handy_window) and close this one, please?

**Comment by whiskeyPeak** [comment] 2023-02-13 06:55
Done!

See https://github.com/ubuntu-flutter-community/handy_window/issues/31

**Closed** 2023-02-13 06:55 UTC
